version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - currency_network

  app:
    image: tomcat:10-jdk11-openjdk
    container_name: tomcat_app
    depends_on:
      - db
    environment:
      DB_URL: "jdbc:postgresql://db:5432/postgres"
      DB_USER: "myuser"
      DB_PASS: "mysecretpassword"
    ports:
      - "8080:8080"
    networks:
      - currency_network

  frontend:
    image: nginx:latest
    container_name: currency_exchange_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - currency_network

networks:
  currency_network:
    driver: bridge

volumes:
  postgres_data:
